checkpoint_name: tutorial_checkpoint
data_bucket: ge-data-bucket-jorik
docker_image_name: tutorial_image
expectations_suite_name: tutorial_test_suite
prefix_example: data/
run_name_template: Tutorial run %d-%m-%Y
site_bucket: ge-site-bucket-jorik
site_bucket_prefix: ''
site_name: Tutorial expectations
store_bucket: ge-store-bucket-jorik
store_bucket_prefix: expectations
